spring.application.name=personal_blog
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
debug=true
spring.datasource.url=${POSTGRES_DB_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.jpa.properties.hibernate.default_schema=${POSTGRES_DB}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.type.preferred_instant_jdbc_type=TIMESTAMP
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=TRACE